spring.application.name=ecom-application

# H2 Database
#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# JPA
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=Ecommerce Application
info.app.description=App build by me
info.app.version=1.0.0
management.endpoint.shutdown.enabled=true
management.server.shutdown=graceful

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb
spring.datasource.username=embarkx
spring.datasource.password=embarkx
spring.jpa.database=POSTGRESQL
